import 'package:dotto/domain/floor.dart';
import 'package:dotto/domain/map_stair_type.dart';
import 'package:dotto/domain/map_tile_props.dart';
import 'package:dotto/domain/restroom_type.dart';
import 'package:dotto/domain/room_equipment.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final funMapProvider = Provider<List<MapTileProps>>((ref) => FUNMap.tileProps);

abstract class FUNMap {
  static final List<MapTileProps> tileProps = [
    /// 1F
    AtriumMapTileProps(floor: Floor.first, width: 40, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.first, width: 8, height: 7, top: 1, right: 1, bottom: 0, left: 1, id: null),
    AisleMapTileProps(floor: Floor.first, width: 40, height: 1, top: 1, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.first, width: 2, height: 3, top: 0, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.first, width: 6, height: 4, top: 0, right: 1, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.first, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.first, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 0, id: null),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '155'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '154'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '153'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '152'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '151'),
    AisleMapTileProps(floor: Floor.first, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    // アトリエ側トイレ
    RestroomMapTileProps(
      floor: Floor.first,
      width: 3,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.kitchenette],
    ),
    OtherRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '150'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '149'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '148'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '147'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '146'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '145'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '144'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '143'),
    // 食堂側トイレ
    RestroomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.women],
    ),
    AisleMapTileProps(floor: Floor.first, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    // 食堂側トイレ
    RestroomMapTileProps(
      floor: Floor.first,
      width: 3,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.multipurpose],
    ),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '135'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '134'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '133'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '132'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '131'),
    StairMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '130'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '129'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '128'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '127'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '126'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '125'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '124'),
    FacultyRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '123'),
    SubRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '122'),
    OtherRoomMapTileProps(floor: Floor.first, width: 1, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.first, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '121'),
    StairMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    SubRoomMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 16,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: '食堂',
      label: '食堂',
    ),
    AisleMapTileProps(floor: Floor.first, width: 42, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.first, width: 12, height: 6, top: 0, right: 0, bottom: 0, left: 1, id: null),
    AisleMapTileProps(floor: Floor.first, width: 6, height: 10, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.first, width: 18, height: 3, top: 0, right: 1, bottom: 0, left: 1, id: null),
    AisleMapTileProps(floor: Floor.first, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    ElevatorMapTileProps(floor: Floor.first, width: 2, height: 2, top: 1, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 18, height: 3, top: 0, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 1, top: 0, right: 0, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 6, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    // アトリエ
    ClassroomMapTileProps(
      floor: Floor.first,
      width: 12,
      height: 6,
      top: 0,
      right: 0,
      bottom: 1,
      left: 1,
      id: 'アトリエ',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AisleMapTileProps(floor: Floor.first, width: 18, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 1,
      label: 'プレゼンテーションベイB',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      label: 'プレゼンテーションベイG',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 5,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      label: 'プレゼンテーションベイR',
    ),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 1, left: 0),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: null,
      label: '出入口',
    ),
    AisleMapTileProps(floor: Floor.first, width: 2, height: 2, top: 0, right: 0, bottom: 1, left: 0),

    /// 2F
    AisleMapTileProps(floor: Floor.second, width: 40, height: 1, top: 1, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.second, width: 2, height: 3, top: 1, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.second, width: 6, height: 7, top: 1, right: 1, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.second, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 1),
    FacultyRoomMapTileProps(floor: Floor.second, width: 3, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '255'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '254'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '253'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '252'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '251'),
    AisleMapTileProps(floor: Floor.second, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    // アトリエ側トイレ
    RestroomMapTileProps(
      floor: Floor.second,
      width: 3,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.kitchenette],
    ),
    OtherRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '250'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '249'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '248'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '247'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '246'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '245'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '244'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '243'),
    // 購買側トイレ
    RestroomMapTileProps(
      floor: Floor.second,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.women],
    ),
    AisleMapTileProps(floor: Floor.second, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    // 購買側トイレ
    RestroomMapTileProps(
      floor: Floor.second,
      width: 3,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.multipurpose],
    ),
    OtherRoomMapTileProps(floor: Floor.second, width: 1, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: null),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '235'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '234'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '233'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '232'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '231'),
    // アトリエ側階段
    StairMapTileProps(
      floor: Floor.second,
      width: 2,
      height: 4,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '230'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '229'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '228'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '227'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '226'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '225'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '224'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '223'),
    FacultyRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '222'),
    OtherRoomMapTileProps(floor: Floor.second, width: 1, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.second, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '221'),
    // 購買側階段
    StairMapTileProps(
      floor: Floor.second,
      width: 2,
      height: 4,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    AisleMapTileProps(floor: Floor.second, width: 42, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    // 購買
    SubRoomMapTileProps(
      floor: Floor.second,
      width: 6,
      height: 6,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: '購買',
      label: '購買',
    ),
    OtherRoomMapTileProps(floor: Floor.second, width: 12, height: 5, top: 0, right: 0, bottom: 1, left: 1, id: null),
    AisleMapTileProps(floor: Floor.second, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.second, width: 17, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.second, width: 1, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.second, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.second, width: 4, height: 4, top: 0, right: 0, bottom: 1, left: 0),
    StairMapTileProps(
      floor: Floor.second,
      width: 2,
      height: 4,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.vertical, up: false, down: true),
    ),
    AisleMapTileProps(floor: Floor.second, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    StairMapTileProps(
      floor: Floor.second,
      width: 2,
      height: 4,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.vertical, up: false, down: true),
    ),
    AisleMapTileProps(floor: Floor.second, width: 18, height: 3, top: 0, right: 0, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.second, width: 36, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.second, width: 2, height: 6, top: 0, right: 0, bottom: 1, left: 1),
    AtriumMapTileProps(floor: Floor.second, width: 10, height: 2, top: 1, right: 0, bottom: 0, left: 1),
    ElevatorMapTileProps(floor: Floor.second, width: 2, height: 2, top: 1, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.second, width: 8, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.second, width: 2, height: 1, top: 0, right: 1, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.second, width: 8, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.second, width: 10, height: 1, top: 0, right: 0, bottom: 0, left: 1),

    /// 3F
    // 体育館
    ClassroomMapTileProps(
      floor: Floor.third,
      width: 12,
      height: 18,
      top: 1,
      right: 0,
      bottom: 0,
      left: 1,
      id: '体育館',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.unavailable),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    SubRoomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 6,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: 'トレーニングルーム',
      label: 'トレーニングルーム',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.unknown),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AtriumMapTileProps(floor: Floor.third, width: 30, height: 6, top: 0, right: 0, bottom: 0, left: 1),
    // 体育館トイレ
    RestroomMapTileProps(
      floor: Floor.third,
      width: 4,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.multipurpose],
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    // 工房
    ClassroomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 12,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: '工房',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    // エレクトロニクス工房
    ClassroomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 12,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: 'エレクトロニクス工房',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    SubRoomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 2,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: '医務室',
      label: '医務室',
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, label: '休日夜間入口'),
    OtherRoomMapTileProps(floor: Floor.third, width: 6, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.third, width: 4, height: 3, top: 1, right: 1, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '映像音響スタジオ',
      label: '映像音響スタジオ',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.unknown),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 10, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.third, width: 4, height: 3, top: 0, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.third, width: 6, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.third, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.third, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    // 体育館側階段
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 7,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      id: 'ミュージアム',
      label: 'ミュージアム',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AisleMapTileProps(floor: Floor.third, width: 6, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '社会連携センター',
      label: '社会連携センター',
    ),
    // 駐車場側トイレ
    RestroomMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women],
    ),
    // 事務局行き階段
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 5,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    OtherRoomMapTileProps(floor: Floor.third, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    // モール
    AisleMapTileProps(floor: Floor.third, width: 48, height: 2, top: 0, right: 1, bottom: 0, left: 1),
    OtherRoomMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: null,
      label: '研究棟入口',
    ),
    AisleMapTileProps(floor: Floor.third, width: 12, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    // モール体育館側階段
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AisleMapTileProps(floor: Floor.third, width: 18, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    // モールエレベーター
    ElevatorMapTileProps(floor: Floor.third, width: 2, height: 2, top: 1, right: 0, bottom: 1, left: 1),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    // モール入口側階段
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AisleMapTileProps(floor: Floor.third, width: 6, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: null,
      label: '正面\n入口',
    ),
    // モール
    AisleMapTileProps(floor: Floor.third, width: 48, height: 2, top: 0, right: 1, bottom: 0, left: 1),
    // 大講義室
    ClassroomMapTileProps(
      floor: Floor.third,
      width: 12,
      height: 7,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
      id: '大講義室',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    OtherRoomMapTileProps(floor: Floor.third, width: 1, height: 7, top: 0, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(
      floor: Floor.third,
      width: 3,
      height: 5,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '心理学実験室',
      label: '心理学実験室',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.unknown),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    ClassroomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 7,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '365',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 7,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '364',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 7,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '363',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    OtherRoomMapTileProps(floor: Floor.third, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    // ライブラリ
    SubRoomMapTileProps(
      floor: Floor.third,
      width: 6,
      height: 37,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      id: 'ライブラリ',
      label: 'ライブラリ',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    // 入口側トイレ男
    RestroomMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 5,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men],
    ),
    OtherRoomMapTileProps(floor: Floor.third, width: 2, height: 5, top: 0, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.third, width: 3, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.third, width: 42, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.third, width: 1, height: 6, top: 0, right: 0, bottom: 0, left: 1),
    FacultyRoomMapTileProps(floor: Floor.third, width: 3, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '355'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '354'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '353'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '352'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '351'),
    // 331側トイレ
    RestroomMapTileProps(
      floor: Floor.third,
      width: 4,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.kitchenette],
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '350'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '349'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '348'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '347'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '346'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '345'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '344'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '343'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: '342'),
    // 入口側トイレ女
    RestroomMapTileProps(
      floor: Floor.third,
      width: 4,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.women, RestroomType.multipurpose],
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.third, width: 1, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: null),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '335'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '334'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '333'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '332'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '331'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '330'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '329'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '328'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '327'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '326'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '325'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '324'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '323'),
    FacultyRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '322'),
    SubRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '321'),
    OtherRoomMapTileProps(floor: Floor.third, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.third, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.third, width: 42, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.third, width: 12, height: 5, top: 0, right: 0, bottom: 1, left: 1, id: null),
    AisleMapTileProps(floor: Floor.third, width: 4, height: 3, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.third, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.third, width: 14, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.third, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 4, height: 3, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    // 階段331側下り
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 4,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.vertical, up: false, down: true),
    ),
    // 階段321側下り
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 4,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.vertical, up: false, down: true),
    ),
    AisleMapTileProps(floor: Floor.third, width: 18, height: 3, top: 0, right: 0, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 1, left: 0),
    // 階段331側上り
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    // 階段321側上り
    StairMapTileProps(
      floor: Floor.third,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AtriumMapTileProps(floor: Floor.third, width: 36, height: 12, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 12, top: 0, right: 0, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.third, width: 4, height: 8, top: 0, right: 0, bottom: 0, left: 1),
    // エレベーター
    ElevatorMapTileProps(floor: Floor.third, width: 2, height: 2, top: 1, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.third, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.third, width: 2, height: 1, top: 0, right: 1, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.third, width: 2, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.third, width: 4, height: 1, top: 0, right: 0, bottom: 0, left: 1),

    /// 4F
    // 体育館
    OtherRoomMapTileProps(
      floor: Floor.fourth,
      width: 12,
      height: 18,
      top: 1,
      right: 1,
      bottom: 1,
      left: 1,
      id: '体育館',
      label: '体育館',
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 36, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 6, top: 1, right: 0, bottom: 0, left: 0),
    // 体育館側トイレ
    RestroomMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 4,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.multipurpose],
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 6, top: 0, right: 0, bottom: 1, left: 0),
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 6,
      top: 1,
      right: 0,
      bottom: 0,
      left: 1,
      id: '495C&D',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 6,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: '494C&D',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 6,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: '493',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 6, top: 1, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 6, top: 1, right: 0, bottom: 1, left: 0),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 2,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: '証明書発行機',
      label: '証明書発行機',
    ),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 10,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      id: '事務局',
      label: '事務局',
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    // 体育館側階段
    StairMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 30, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 13, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 2, height: 5, top: 0, right: 1, bottom: 1, left: 0, id: '406'),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 5, top: 1, right: 0, bottom: 0, left: 0),
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 1,
      id: '485',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.unavailable),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      id: '484',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      id: '483',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 13, top: 0, right: 0, bottom: 0, left: 0),
    // 事務側トイレ
    RestroomMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.multipurpose],
    ),
    StairMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 5,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.vertical, up: false, down: true),
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 5,
      height: 2,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: '局長室',
      label: '局長室',
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 12, height: 6, top: 0, right: 1, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fourth, width: 22, height: 2, top: 0, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fourth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.fourth, width: 1, height: 8, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fourth, width: 5, height: 6, top: 0, right: 0, bottom: 0, left: 1),
    // モール体育館側
    StairMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 18, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    ElevatorMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 1, left: 1),
    // モール正面玄関側
    StairMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fourth, width: 22, height: 2, top: 0, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fourth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 1),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 1, id: 'S-15'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-14'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-13'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-12'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-11'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-10'),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 1, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: null),
    RestroomMapTileProps(
      floor: Floor.fourth,
      width: 1,
      height: 2,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      types: [RestroomType.kitchenette],
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 0, right: 0, bottom: 1, left: 0),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 1, id: 'S-9'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-8'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-7'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-6'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-5'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-4'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-3'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-2'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: 'S-1'),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 1, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(
      floor: Floor.fourth,
      width: 1,
      height: 2,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      id: null,
      label: '倉庫',
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 0, right: 1, bottom: 1, left: 0),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 3,
      height: 3,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      id: '理事室',
      label: '理事室',
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 43, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 5,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '秘書室',
      label: '秘書室',
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 1, height: 4, top: 0, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(
      floor: Floor.fourth,
      width: 1,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: null,
      label: '倉庫',
    ),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '435'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '434'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '433'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '432'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '431'),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    RestroomMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 3,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women],
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 10, top: 1, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(
      floor: Floor.fourth,
      width: 1,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
      id: null,
      label: '印刷',
    ),
    AisleMapTileProps(floor: Floor.fourth, width: 1, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '429'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '428'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '427'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '426'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '425'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '424'),
    FacultyRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '423'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '422'),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    RestroomMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 3,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women],
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 10, top: 1, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 1, height: 9, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 3,
      height: 4,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      id: '学長室',
      label: '学長室',
    ),
    OtherRoomMapTileProps(
      floor: Floor.fourth,
      width: 1,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
      id: null,
      label: '倉庫',
    ),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 2, height: 1, top: 0, right: 1, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 2, height: 1, top: 0, right: 1, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.fourth, width: 14, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 3, top: 0, right: 1, bottom: 0, left: 0, id: 'M402'),
    AisleMapTileProps(floor: Floor.fourth, width: 22, height: 1, top: 0, right: 1, bottom: 0, left: 1),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 5,
      height: 4,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      id: '特別応接室',
      label: '特別応接室',
    ),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 12, height: 5, top: 0, right: 0, bottom: 1, left: 1, id: null),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 5, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 18, height: 3, top: 0, right: 0, bottom: 0, left: 1, id: null),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 5, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 5, top: 0, right: 1, bottom: 1, left: 0, label: 'ラウンジ'),
    SubRoomMapTileProps(floor: Floor.fourth, width: 2, height: 3, top: 0, right: 1, bottom: 1, left: 0, id: 'M401'),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 6, height: 2, top: 0, right: 0, bottom: 1, left: 1, id: null),
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 2,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      id: 'メタ学習ラボ',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.unavailable),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.unavailable),
      ),
    ),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 6, height: 2, top: 0, right: 0, bottom: 1, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.fourth, width: 4, height: 1, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.fourth, width: 1, height: 1, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 6, height: 1, top: 0, right: 1, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fourth, width: 12, height: 19, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fourth, width: 22, height: 5, top: 0, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fourth, width: 4, height: 5, top: 0, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.fourth, width: 1, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 3,
      height: 3,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: 'サーバーコンピュータ事務室',
      label: 'サーバーコンピュータ事務室',
    ),
    // サーバーコンピュータ室側トイレ
    RestroomMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 3,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.kitchenette],
    ),
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 5,
      height: 4,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      id: 'サーバーコンピュータ室',
      label: 'サーバーコンピュータ室',
    ),
    StairMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 20, height: 2, top: 0, right: 1, bottom: 1, left: 0),
    StairMapTileProps(
      floor: Floor.fourth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 26, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fourth, width: 4, height: 8, top: 0, right: 1, bottom: 0, left: 1),
    // 講堂
    ClassroomMapTileProps(
      floor: Floor.fourth,
      width: 6,
      height: 12,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      id: '講堂',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    // デルタビスタ
    SubRoomMapTileProps(
      floor: Floor.fourth,
      width: 4,
      height: 11,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: 'デルタビスタ',
      label: 'デルタビスタ',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.limited),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.available),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AtriumMapTileProps(floor: Floor.fourth, width: 20, height: 11, top: 1, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 2, height: 9, top: 0, right: 0, bottom: 0, left: 0),
    ElevatorMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 1, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fourth, width: 2, height: 2, top: 0, right: 1, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.fourth, width: 6, height: 2, top: 0, right: 0, bottom: 1, left: 0),

    /// 5F
    // サークル1
    OtherRoomMapTileProps(floor: Floor.fifth, width: 14, height: 2, top: 1, right: 0, bottom: 0, left: 1, id: null),
    // サークル3
    OtherRoomMapTileProps(floor: Floor.fifth, width: 2, height: 10, top: 1, right: 1, bottom: 0, left: 0, id: null),
    AtriumMapTileProps(floor: Floor.fifth, width: 32, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 14, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.fifth, width: 1, height: 14, top: 0, right: 0, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fifth, width: 11, height: 14, top: 1, right: 1, bottom: 1, left: 1),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 9, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 6, top: 0, right: 0, bottom: 1, left: 0),
    ClassroomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 6,
      top: 1,
      right: 0,
      bottom: 0,
      left: 1,
      id: '595',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 6,
      top: 1,
      right: 0,
      bottom: 0,
      left: 0,
      id: '594',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 6,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      id: '593',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 6, height: 6, top: 0, right: 1, bottom: 1, left: 0),
    SubRoomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 12,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      id: '共同研究室',
      label: '共同研究室',
    ),
    // 階段体育館側
    StairMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    AisleMapTileProps(floor: Floor.fifth, width: 30, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    // 体育館側トイレ
    RestroomMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 5,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.multipurpose],
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 5, top: 1, right: 0, bottom: 0, left: 0),
    ClassroomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 1,
      id: '585',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      id: '584',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      id: '583',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 5, top: 0, right: 0, bottom: 0, left: 0),
    // 事務側トイレ
    RestroomMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 5,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      types: [RestroomType.men, RestroomType.women],
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 5, top: 1, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 14, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fifth, width: 12, height: 6, top: 1, right: 1, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 22, height: 2, top: 0, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 6, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 10, height: 2, top: 0, right: 0, bottom: 0, left: 1),
    // 階段center側
    StairMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 18, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    // エレベーターcenter
    ElevatorMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 1, right: 0, bottom: 1, left: 1),
    // 階段right側
    StairMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 8, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 22, height: 2, top: 0, right: 1, bottom: 1, left: 1),
    AtriumMapTileProps(floor: Floor.fifth, width: 10, height: 2, top: 0, right: 0, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.fifth, width: 38, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.fifth, width: 2, height: 5, top: 1, right: 1, bottom: 0, left: 0, id: null),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 5, top: 0, right: 1, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 5, top: 1, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(
      floor: Floor.fifth,
      width: 4,
      height: 8,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      id: '会議室',
      label: '会議室',
    ),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 1, id: '536'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '535'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '534'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '533'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '532'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '531'),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 1, bottom: 0, left: 0, id: null),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 1, right: 0, bottom: 1, left: 0),
    RestroomMapTileProps(
      floor: Floor.fifth,
      width: 1,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
      types: [RestroomType.kitchenette],
    ),
    AisleMapTileProps(floor: Floor.fifth, width: 1, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '529'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '528'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '527'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '526'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '525'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '524'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '523'),
    FacultyRoomMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: '522'),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 44, height: 1, top: 0, right: 0, bottom: 0, left: 1),
    // スタジオleft
    OtherRoomMapTileProps(floor: Floor.fifth, width: 12, height: 2, top: 0, right: 0, bottom: 1, left: 1, id: null),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 2,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: '大学生協学生委員室',
      label: '大学生協学生委員室',
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 1, right: 0, bottom: 0, left: 0),
    // スタジオcenter
    OtherRoomMapTileProps(floor: Floor.fifth, width: 18, height: 2, top: 0, right: 0, bottom: 1, left: 1, id: null),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 11, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 0, right: 1, bottom: 1, left: 0, id: 'M502'),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 1, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 12, height: 12, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 12, top: 0, right: 0, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 22, height: 10, top: 0, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fifth, width: 4, height: 9, top: 0, right: 1, bottom: 1, left: 1),
    SubRoomMapTileProps(floor: Floor.fifth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'M501'),
    AisleMapTileProps(floor: Floor.fifth, width: 6, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 1, height: 5, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.fifth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    AisleMapTileProps(floor: Floor.fifth, width: 1, height: 5, top: 0, right: 1, bottom: 0, left: 0),
    // 講堂側トイレ
    RestroomMapTileProps(
      floor: Floor.fifth,
      width: 4,
      height: 3,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.multipurpose],
    ),
    AisleMapTileProps(floor: Floor.fifth, width: 12, height: 1, top: 0, right: 1, bottom: 0, left: 0),
    // 階段center側
    StairMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 20, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    // 階段講堂側
    StairMapTileProps(
      floor: Floor.fifth,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 1, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(
      floor: Floor.fifth,
      width: 4,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '調整室',
      label: '調整室',
    ),
    AisleMapTileProps(floor: Floor.fifth, width: 1, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 36, height: 12, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 12, top: 0, right: 0, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 4, height: 8, top: 0, right: 1, bottom: 0, left: 1),
    // 講堂
    ClassroomMapTileProps(
      floor: Floor.fifth,
      width: 6,
      height: 12,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: '講堂',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    // エレベーター
    ElevatorMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 1, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.fifth, width: 2, height: 1, top: 0, right: 1, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 2, height: 1, top: 0, right: 1, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 4, height: 1, top: 0, right: 1, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.fifth, width: 42, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.fifth, width: 6, height: 7, top: 0, right: 0, bottom: 0, left: 0),

    /// R6F
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 1, right: 0, bottom: 0, left: 1, id: 'R611'),
    AisleMapTileProps(floor: Floor.sixth, width: 1, height: 30, top: 1, right: 0, bottom: 1, left: 0),
    OtherRoomMapTileProps(floor: Floor.sixth, width: 3, height: 3, top: 1, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.sixth, width: 3, height: 3, top: 1, right: 0, bottom: 0, left: 0, id: 'R627'),
    AisleMapTileProps(floor: Floor.sixth, width: 2, height: 30, top: 1, right: 0, bottom: 1, left: 0),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 4, top: 1, right: 0, bottom: 0, left: 0, id: 'R637'),
    AisleMapTileProps(floor: Floor.sixth, width: 4, height: 14, top: 1, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.sixth, width: 1, height: 24, top: 1, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 1, right: 1, bottom: 0, left: 0, id: 'R657'),
    AtriumMapTileProps(floor: Floor.sixth, width: 22, height: 30, top: 0, right: 0, bottom: 0, left: 0),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R610'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R656'),
    AisleMapTileProps(floor: Floor.sixth, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.sixth, width: 3, height: 20, top: 0, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.sixth, width: 3, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R626'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R636'),
    AisleMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    StairMapTileProps(
      floor: Floor.sixth,
      width: 4,
      height: 2,
      top: 1,
      right: 0,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    StairMapTileProps(
      floor: Floor.sixth,
      width: 4,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R609'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 3, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R625'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 3, top: 0, right: 0, bottom: 0, left: 0, id: 'R635'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R655'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R608'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R654'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 3, top: 0, right: 0, bottom: 0, left: 0, id: 'R634'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R607'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 3, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R624'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R653'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R606'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: 'R633'),
    OtherRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R652'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R605'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 3, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R623'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R632'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R642'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 6, top: 0, right: 1, bottom: 0, left: 0, id: 'R651'),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R604'),
    StairMapTileProps(
      floor: Floor.sixth,
      width: 4,
      height: 2,
      top: 1,
      right: 0,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.horizontal, up: true, down: false),
    ),
    SubRoomMapTileProps(floor: Floor.sixth, width: 3, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R622'),
    AisleMapTileProps(floor: Floor.sixth, width: 8, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R631'),
    ElevatorMapTileProps(floor: Floor.sixth, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    StairMapTileProps(
      floor: Floor.sixth,
      width: 2,
      height: 2,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    OtherRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: null),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R603'),
    AisleMapTileProps(floor: Floor.sixth, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(floor: Floor.sixth, width: 5, height: 4, top: 0, right: 1, bottom: 0, left: 0, id: 'R641'),
    AtriumMapTileProps(floor: Floor.sixth, width: 4, height: 6, top: 1, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.sixth, width: 3, height: 5, top: 0, right: 0, bottom: 1, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.sixth, width: 3, height: 3, top: 0, right: 0, bottom: 0, left: 0, id: 'R621'),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R602'),
    RestroomMapTileProps(
      floor: Floor.sixth,
      width: 4,
      height: 4,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.multipurpose],
    ),
    FacultyRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 1, left: 1, id: 'R601'),
    OtherRoomMapTileProps(floor: Floor.sixth, width: 2, height: 2, top: 0, right: 0, bottom: 1, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.sixth, width: 1, height: 2, top: 0, right: 0, bottom: 1, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.sixth, width: 4, height: 2, top: 0, right: 0, bottom: 1, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.sixth, width: 1, height: 2, top: 0, right: 1, bottom: 1, left: 0, id: null),

    /// R7F
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 1, right: 0, bottom: 0, left: 1, id: 'R711'),
    AisleMapTileProps(floor: Floor.seventh, width: 1, height: 30, top: 1, right: 0, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.seventh, width: 3, height: 3, top: 0, right: 0, bottom: 1, left: 1),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 2, height: 3, top: 1, right: 1, bottom: 0, left: 1, id: null),
    AtriumMapTileProps(floor: Floor.seventh, width: 3, height: 3, top: 0, right: 0, bottom: 1, left: 0),
    AtriumMapTileProps(floor: Floor.seventh, width: 2, height: 3, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 2, height: 9, top: 1, right: 1, bottom: 0, left: 1, id: null),
    AtriumMapTileProps(floor: Floor.seventh, width: 4, height: 9, top: 0, right: 1, bottom: 1, left: 0),
    AisleMapTileProps(floor: Floor.seventh, width: 1, height: 14, top: 1, right: 0, bottom: 0, left: 0),
    FacultyRoomMapTileProps(
      floor: Floor.seventh,
      width: 4,
      height: 2,
      top: 1,
      right: 1,
      bottom: 0,
      left: 0,
      id: 'R757',
    ),
    AtriumMapTileProps(floor: Floor.seventh, width: 22, height: 20, top: 0, right: 0, bottom: 1, left: 0),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R710'),
    FacultyRoomMapTileProps(
      floor: Floor.seventh,
      width: 4,
      height: 2,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
      id: 'R756',
    ),
    AisleMapTileProps(floor: Floor.seventh, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.seventh, width: 2, height: 22, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.seventh, width: 2, height: 6, top: 0, right: 0, bottom: 1, left: 1),
    AisleMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.seventh, width: 6, height: 4, top: 1, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0),
    StairMapTileProps(
      floor: Floor.seventh,
      width: 4,
      height: 2,
      top: 1,
      right: 0,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    StairMapTileProps(
      floor: Floor.seventh,
      width: 4,
      height: 2,
      top: 1,
      right: 1,
      bottom: 1,
      left: 0,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R709'),
    AtriumMapTileProps(floor: Floor.seventh, width: 4, height: 12, top: 0, right: 0, bottom: 0, left: 1),
    SubRoomMapTileProps(floor: Floor.seventh, width: 2, height: 4, top: 1, right: 0, bottom: 0, left: 1, id: 'R725'),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R755'),
    AisleMapTileProps(floor: Floor.seventh, width: 8, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 1, id: null),
    AtriumMapTileProps(floor: Floor.seventh, width: 8, height: 4, top: 1, right: 1, bottom: 1, left: 1),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R754'),
    SubRoomMapTileProps(floor: Floor.seventh, width: 2, height: 4, top: 0, right: 0, bottom: 0, left: 1, id: 'R724'),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 1, bottom: 0, left: 0, id: 'R753'),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R706'),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 9, height: 6, top: 0, right: 1, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R705'),
    SubRoomMapTileProps(floor: Floor.seventh, width: 2, height: 4, top: 0, right: 0, bottom: 1, left: 1, id: 'R723'),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 4, top: 0, right: 0, bottom: 0, left: 0, id: 'R731'),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R704'),
    StairMapTileProps(
      floor: Floor.seventh,
      width: 4,
      height: 2,
      top: 1,
      right: 0,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.horizontal, up: false, down: true),
    ),
    AtriumMapTileProps(floor: Floor.seventh, width: 6, height: 4, top: 0, right: 1, bottom: 1, left: 1),
    AisleMapTileProps(floor: Floor.seventh, width: 30, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    ClassroomMapTileProps(
      floor: Floor.seventh,
      width: 5,
      height: 10,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: 'R791',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.limited),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AisleMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.seventh, width: 3, height: 3, top: 1, right: 1, bottom: 0, left: 1),
    AisleMapTileProps(floor: Floor.seventh, width: 1, height: 7, top: 0, right: 0, bottom: 0, left: 0),
    ElevatorMapTileProps(floor: Floor.seventh, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    StairMapTileProps(
      floor: Floor.seventh,
      width: 2,
      height: 2,
      top: 0,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: false, down: true),
    ),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: 'R751'),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 5, height: 2, top: 0, right: 0, bottom: 0, left: 0, id: null),
    ClassroomMapTileProps(
      floor: Floor.seventh,
      width: 4,
      height: 8,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      id: 'R781',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.limited),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ClassroomMapTileProps(
      floor: Floor.seventh,
      width: 4,
      height: 8,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      id: 'R782',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.limited),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    ElevatorMapTileProps(floor: Floor.seventh, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.seventh, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R703'),
    AisleMapTileProps(floor: Floor.seventh, width: 6, height: 1, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.seventh, width: 5, height: 4, top: 1, right: 0, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.seventh, width: 9, height: 6, top: 1, right: 1, bottom: 0, left: 0),
    AisleMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    AtriumMapTileProps(floor: Floor.seventh, width: 3, height: 5, top: 1, right: 0, bottom: 0, left: 1),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 2, height: 5, top: 0, right: 0, bottom: 1, left: 1, id: null),
    AtriumMapTileProps(floor: Floor.seventh, width: 3, height: 3, top: 1, right: 0, bottom: 0, left: 1),
    AtriumMapTileProps(floor: Floor.seventh, width: 3, height: 1, top: 0, right: 1, bottom: 0, left: 0),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 0, left: 1, id: 'R702'),
    RestroomMapTileProps(
      floor: Floor.seventh,
      width: 3,
      height: 4,
      top: 1,
      right: 0,
      bottom: 1,
      left: 1,
      types: [RestroomType.men, RestroomType.women],
    ),
    StairMapTileProps(
      floor: Floor.seventh,
      width: 1,
      height: 2,
      top: 0,
      right: 1,
      bottom: 1,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    AisleMapTileProps(floor: Floor.seventh, width: 1, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    RestroomMapTileProps(
      floor: Floor.seventh,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.multipurpose],
    ),
    SubRoomMapTileProps(floor: Floor.seventh, width: 4, height: 2, top: 0, right: 0, bottom: 1, left: 1, id: 'R701'),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 1, height: 2, top: 1, right: 1, bottom: 1, left: 0, id: null),
    AtriumMapTileProps(floor: Floor.seventh, width: 2, height: 2, top: 0, right: 0, bottom: 0, left: 0),
    OtherRoomMapTileProps(floor: Floor.seventh, width: 5, height: 2, top: 1, right: 1, bottom: 1, left: 0, id: null),
    RestroomMapTileProps(
      floor: Floor.seventh,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      types: [RestroomType.women],
    ),
    RestroomMapTileProps(
      floor: Floor.seventh,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      types: [RestroomType.men],
    ),
    RestroomMapTileProps(floor: Floor.seventh, width: 1, height: 1, top: 0, right: 0, bottom: 1, left: 0, types: []),
  ];
}
