include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - apps/dotto/lib/**/*.freezed.dart
    - apps/dotto/lib/**/*.g.dart
    - apps/dotto/test/**/*.mocks.dart
    - packages/dotto_api/**
    - packages/dotto_design_system/lib/**/*.g.dart
formatter:
  page_width: 80
  trailing_commas: automate
linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
