[settings]
minimum_release_age = "7d"

[settings.ruby]
compile = false

[env]
_.path = ["{{env.HOME}}/.pub-cache/bin"]

[tools]
"aqua:go-task/task" = "3.50.0"
flutter = "3.44.0"
gcloud = "567.0.0"
java = "25.0.2"
node = "24.15.0"
"npm:firebase-tools" = "15.15.0"
"npm:@openapitools/openapi-generator-cli" = "2.32.0"
ruby = "4.0.4"

[tasks.pre-commit]
run = "dart run scripts/pre_commit.dart"

[tasks.setup]
run = [
  "bundle install",
  "dart pub global activate melos",
  "dart pub global activate flutterfire_cli",
  "melos bootstrap",
  "melos run setup:flutterfire",
  "melos run fetch:dart_defines"
]

[tasks.setup-ci]
run = [
  "bundle install",
  "dart pub global activate melos",
  "dart pub global activate flutterfire_cli",
  "melos bootstrap"
]

[tasks.build]
run = "melos run gen:build_runner --no-select"

[tasks.app]
run = [
  "melos run gen:build_runner --no-select",
  "cd apps/dotto && flutter run --dart-define-from-file=./dart_defines/development.json",
]

[tasks.widgetbook]
run = [
  "melos run gen:build_runner --no-select",
  "cd packages/dotto_design_system && flutter run",
]

[tasks.test-unit]
run = "melos run test:unit"

[tasks.analyze]
run = "dart analyze apps/dotto/ packages/dotto_design_system/ scripts/"

[tasks.format]
run = "dart fix --apply && dart format apps/dotto/ packages/dotto_design_system/ scripts/"

[tasks.generate-openapi]
run = "openapi-generator-cli generate -i ./openapi/openapi.yaml -g dart-dio -o ./packages/dotto_api"
