[settings]
minimum_release_age = "14d"

[settings.ruby]
compile = false

[tools]
"aqua:go-task/task" = "3.50.0"
dotenvx = "1.65.0"
flutter = "3.41.9"
"github:linux-test-project/lcov" = "2.4"
java = "25.0.2"
"npm:firebase-tools" = "15.15.0"
"npm:@openapitools/openapi-generator-cli" = "2.32.0"
ruby = "4.0.4"

[tasks.pre-commit]
description = "Run pre-commit checks"
run = "dart run scripts/pre_commit.dart"
