# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

require "yaml"

pubspec = YAML.load_file(File.expand_path("../pubspec.yaml", Dir.pwd))
app_version pubspec.fetch("version").to_s.split("+").first
