version: "3"

vars:
  DOTENVX: mise x -- dotenvx
  FASTLANE: mise x -- bundle exec fastlane

tasks:
  download-appstore-metadata-and-screenshots:
    desc: Download App Store metadata and screenshots
    cmds:
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} deliver download_metadata"
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} deliver download_screenshots"

  upload-appstore-metadata-and-screenshots:
    desc: Upload App Store metadata and screenshots
    cmds:
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} deliver --skip_binary_upload --force"

  deploy-firebase-app-distribution:
    desc: Deploy iOS to Firebase App Distribution
    cmds:
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} deploy_firebase_app_distribution"

  deploy-testflight:
    desc: Deploy iOS to TestFlight
    cmds:
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} deploy_testflight"

  match-development:
    desc: Match development certificates (readonly)
    cmds:
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} match_development_readonly"

  register-device:
    desc: Register iOS device and update provisioning profiles
    vars:
      NAME: "{{.name}}"
      UDID: "{{.udid}}"
    cmds:
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} run register_device name:{{.NAME}} udid:{{.UDID}}"
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} match_development"
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} match_adhoc"
      - "{{.DOTENVX}} run -f ../.env.keys -- {{.DOTENVX}} run -f ./fastlane/.env -- {{.FASTLANE}} match_appstore"
