name: Format Flutter App

on:
  push:
    branches:
      - main
    paths:
      - flutter/**
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - flutter/**
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./flutter

jobs:
  format:
    name: Format
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - name: Install dependencies
        run: task install-all
      - name: Run format
        run: task format
      - name: Check for diff
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "::error::Code is not formatted. Run 'task format' and commit the changes."
            git diff --name-only
            exit 1
          fi
