name: Test Flutter App

on:
  push:
    branches:
      - main
    paths:
      - Flutter/**
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - Flutter/**
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./Flutter

jobs:
  test:
    name: Test
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cache: false
      - name: Install Dependencies
        run: task install-all
      - name: Run Build
        run: task build-all
      - name: Run Tests
        run: task test
