name: Test Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  test:
    name: Test
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cache: false
          working_directory: .
      - run: mise setup-ci
      - run: mise test-unit
